version: '2'
services:
  ie-server:
    image: interventionengine/ie-server:v1.0.0-rc.1
    ports:
      - "3001"
    volumes:
      - ./config/ie-server:/config
      - ./logs/ie-server:/etc/ie-server/logs
    depends_on:
      - mongo
    env_file:
      - ./config/default.env
    command: dockerize -wait tcp://mongo:27017 -timeout 300s ./server -loadCodes
  ie-ccda-endpoint:
    image: interventionengine/ie-ccda-endpoint:v1.0.0
    ports:
      - "3000"
    depends_on:
      - ie-server
    env_file:
      - ./config/default.env
  ie-multifactorriskservice:
    image: interventionengine/ie-multifactorriskservice:v1.0.0-rc.1
    ports:
      - "9000"
    depends_on:
      - ie-server
      - mongo
    env_file:
      - ./config/default.env
      - ./config/site.env
    command: dockerize -wait tcp://mongo:27017 -timeout 300s ./multifactorriskservice
    # command: dockerize -wait tcp://mongo:27017 -timeout 300s ./mock-service -confirm-mock # for testing only!
  ie-integrator:
    image: interventionengine/ie-integrator:v1.0.0-rc.1
    volumes:
      - ./config/ie-integrator:/config
      - ./data/ie-integrator:/data
      - ./logs/ie-integrator:/etc/ie-integrator/logs
    depends_on:
      - ie-server
      - mongo
      - ie-ccda-endpoint
    env_file:
      - ./config/default.env
      - ./config/site.env
    command: dockerize -wait http://ie-ccda-endpoint:3000 -wait tcp://mongo:27017 -timeout 300s ./integrator
  ie-nginx:
    image: interventionengine/ie-nginx:v1.0.0-rc.1
    ports:
      - "443:443"
    volumes:
      - ./config/ie-nginx:/config
      - ./logs/ie-nginx:/etc/nginx/logs
    depends_on:
      - ie-server
      - ie-multifactorriskservice
    env_file:
      - ./config/default.env
    command: dockerize -template /etc/nginx/nginx.conf.tmpl:/etc/nginx/nginx.conf nginx -g 'daemon off;'
  mongo:
    image: mongo:3.2.10
    ports:
      - "27017"
    volumes:
      - ./data/mongo/db:/data/db
